interface types {
    record calculate-interest-rate-request {
        expiry-date: string,
        ttm: f64,
        currency: string
    }

    record calculate-interest-rate-response {
        code: s16,
        message: string,
        data: f64
    }
}